### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by aweirdgift** [aweirdgift/Bleepy_UI#1]
Toggle bar
*Hindi ko maipakita yung toggle bar, try ko ichange yung color ayaw pa rin. Naiadd ko naman na yung CDN ng font awesome if ever under siya ng icons*

Search Bar
*Yung search bar sana kapag responsive, magstick lang siya sa top or nag adjust ang kaso customize kasi yung search bar na ginawa ko. Lagtawan ko muna, hahanp muna ako ng ay, mastack ako dyan eh"

Log In and Sign Up
Tapos yung sign up and log in dapat kasunod siya nung search bar [katulad nung design ko sa Figma". Dapat ba nakagrid system ako sa navbar or kahit flex lang?

**Comment by reyniel26** [comment]
Noted. Fixing right now

**Comment by reyniel26** [comment]
Done
